---
- name: Install Helm Charts
  with_items: "{{ infranodes_bundle_packages }}"
  # yamllint disable-line rule:line-length
  when: item.chart_ref is defined and ( item.when | default(true) ) and ( item.enabled | default (false) )
  # yamllint enable-line rule:line-length
  kubernetes.core.helm:
    chart_ref: "{{ item.chart_ref | mandatory }}"
    chart_version: "{{ item.chart_version | default() }}"
    create_namespace: "{{ item.create_namespace | default(true) }}"
    release_name: "{{ item.name | mandatory }}"
    release_namespace: "{{ item.namespace | default('default') }}"
    release_values: "{{ item.parameters | default('{}') }}"
    release_state: "{{ item.state | default('present') }}"
    wait: "{{ item.wait | default(false) }}"
    kubeconfig: "{{ openshift_kubeconfig_file }}"
