---
# disable-rule:line-length
- name: drain infranodes from user-workload
  environment:
    KUBECONFIG: "{{ openshift_kubeconfig_file }}"
  ansible.builtin.shell:
    cmd: |
      kubectl --kubeconfig "${KUBECONFIG}" drain -l node-role.kubernetes.io/infra='' --ignore-daemonsets --delete-emptydir-data --grace-period 0 --disable-eviction=true --force
  changed_when: true

- name: Re-enable scheduling on infranodes
  environment:
    KUBECONFIG: "{{ openshift_kubeconfig_file }}"
  ansible.builtin.shell:
    cmd: |
      kubectl --kubeconfig "${KUBECONFIG}" uncordon -l node-role.kubernetes.io/infra=''
  changed_when: true

...
