---
- name: "create infrastructure MachineConfigPool"
  k8s:
    kubeconfig: "{{ openshift_kubeconfig_file }}"
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      metadata:
        name: infra
      spec:
        machineConfigSelector:
          matchExpressions:
            - key: machineconfiguration.openshift.io/role
              operator: In
              values:
                - worker
                - infra
        nodeSelector:
          matchLabels:
            node-role.kubernetes.io/infra: ""

- name: "create infrastructure machine config"
  k8s:
    kubeconfig: "{{ openshift_kubeconfig_file }}"
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      metadata:
        name: 51-infra
        labels:
          node-role.kubernetes.io/infra: ""
      spec:
        config:
          ignition:
            version: 3.2.0

...
