---
- name: install requirements
  include_tasks: requirements.yml

- name: apply labels to nodes
  include_tasks: label.yml

- name: define defaultNodeSelector
  include_tasks: scheduler.yml
  tags:
    - infranodes
    - infranodes.ocp
...
