---
# https://access.redhat.com/solutions/5034771
- name: label infrastructure nodes
  environment:
    LABEL: "{{ infranodes_label }}"
    KUBECONFIG: "{{ openshift_kubeconfig_file }}"
  ansible.builtin.command:
    cmd: |
      kubectl label nodes --kubeconfig ${KUBECONFIG} \
        $(kubectl get nodes --no-headers \
        -o jsonpath='{range .items[*]}{.metadata.name}{\"\n\"}{end}' \
        | grep infra) ${LABEL}
    register: labeloutput
    changed_when: "'already has a value' not in labeloutput.stdout"
    failed_when:  "'error' in labloutput.stdout"

- name: taint infrastructure nodes
  kubernetes.core:

...
