---
# https://access.redhat.com/solutions/5034771
- name: label infrastructure nodes
  ansible.builtin.command:
    cmd: |
      kubectl label nodes --kubeconfig { openshift_kubeconfig_file }} \
        $(kubectl get nodes --no-headers \
        -o jsonpath='{range .items[*]}{.metadata.name}{\"\n\"}{end}' \
        | grep infra) {{ infranodes_label }}
    register: labeloutput
    changed_when: "'already has a value' not in labeloutput.stdout"
    failed_when: "'error' in labloutput.stdout"

- name: taint infrastructure nodes
  ansible.builtin.command:
    cmd: |
      kubectl taint nodes --kubeconfig {{ openshift_kubeconfig_file }} \
        -l {{ infranodes_label_selector }} {{ infranodes_taint }}
    register: taintoutput
    changed_when: "'--overwrite is false' not in labeloutput.stdout"
    failed_when: false
...
