---
- name: apply labels to nodes
  include_tasks: label.yml

- name: create MachineConfigPool & MachineConfig
  include_tasks: machineconfigs.yml

- name: define defaultNodeSelector
  include_tasks: scheduler.yml

- name: move workload to infra nodes
  include_tasks: patch_infrastructure_resources.yml
...
