---
- name: "Patch default IngressController"
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig_file }}"
    state: patched
    definition:
      apiVersion: operator.openshift.io/v1
      kind: IngressController
      metadata:
        name: default
        namespace: openshift-ingress-operator
      spec:
        replicas: |
          {{ ocp_infra_count }}
        nodePlacement:
          nodeSelector:
            matchLabels:
              node-role.kubernetes.io/infra: ""
          tolerations:
            - effect: NoSchedule
              key: infra
              value: reserved
            - effect: NoExecute
              key: infra
              value: reserved
  when: 'infranodes_move_router|default(false)|bool'
  tags:
    - infranodes
    - infranodes.ocp
    - infranodes.router
    - molecule-notest

- name: "Patch ImageRegistry"
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig_file }}"
    state: patched
    definition:
      apiVersion: imageregistry.operator.openshift.io/v1
      kind: Config
      metadata:
        name: cluster
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  namespaces:
                    - openshift-image-registry
                  topologyKey: kubernetes.io/hostname
                weight: 100
        nodeSelector:
          node-role.kubernetes.io/infra: ""
        tolerations:
          - effect: NoSchedule
            key: infra
            value: reserved
          - effect: NoExecute
            key: infra
            value: reserved
  tags:
    - infranodes
    - infranodes.ocp
    - infranodes.registry
    - molecule-notest

- name: "Annotate namespaces with daemonsets correctly"
  environment:
    KUBECONFIG: "{{ openshift_kubeconfig_file }}"
  ansible.builtin.command:
    # yamllint disable-line rule:line-length
    cmd: "kubectl annotate ns {{ infranodes_namespace }} openshift.io/node-selector="
  register: infranodes_annotate
  loop: "{{ infranodes_daemonset_namespaces }}"
  loop_control:
    loop_var: infranodes_namespace
  changed_when: '"openshift-logging annotated" in infranodes_annotate.stdout'
  failed_when: '"error" in infranodes_annotate.stdout'
  tags:
    - infranodes
    - infranodes.ocp
    - infranodes.logging
    - molecule-notest

- name: "Patch openshift-gitops instance"
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig_file }}"
    state: patched
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: ArgoCD
      metadata:
        name: openshift-gitops
        namespace: openshift-gitops
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  namespaces:
                    - openshift-gitops
                  topologyKey: kubernetes.io/hostname
                weight: 100
        nodeSelector:
          node-role.kubernetes.io/infra: ""
        tolerations:
          - effect: NoSchedule
            key: infra
            value: reserved
          - effect: NoExecute
            key: infra
            value: reserved

- name: "Patch OpenShift Pipelines"
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig_file }}"
    state: patched
    definition:
      apiVersion: pipelines.openshift.io/v1alpha1
      kind: GitopsService
      metadata:
        name: cluster
      spec:
        runOnInfra: true
        tolerations:
          - effect: NoSchedule
            key: infra
            value: reserved
          - effect: NoExecute
            key: infra
            value: reserved

...
