---
- name: "Patch default IngressController"
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig_file }}"
    state: patched
    definition:
      apiVersion: operator.openshift.io/v1
      kind: IngressController
      metadata:
        name: default
        namespace: openshift-ingress-operator
      spec:
        replicas: "{{ ocp_infra_count | int }}"
        nodePlacement:
          nodeSelector:
            matchLabels:
              node-role.kubernetes.io/infra: ""
          tolerations:
            - effect: NoSchedule
              key: infra
              value: reserved
            - effect: NoExecute
              key: infra
              value: reserved
  tags:
    - infranodes
    - infranodes.ocp
    - infranodes.router
    - molecule-notest

- name: "Patch ImageRegistry"
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig_file }}"
    state: patched
    definition:
      apiVersion: imageregistry.operator.openshift.io/v1
      kind: Config
      metadata:
        name: cluster
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  namespaces:
                    - openshift-image-registry
                  topologyKey: kubernetes.io/hostname
                weight: 100
        nodeSelector:
          node-role.kubernetes.io/infra: ""
        tolerations:
          - effect: NoSchedule
            key: infra
            value: reserved
          - effect: NoExecute
            key: infra
            value: reserved
  tags:
    - infranodes
    - infranodes.ocp
    - infranodes.registry
    - molecule-notest

- name: "Patch Monitoring"
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig_file }}"
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cluster-monitoring-config
        namespace: openshift-monitoring
      data:
        config.yaml: |+
          alertmanagerMain:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
          prometheusK8s:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
          prometheusOperator:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
          grafana:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
          k8sPrometheusAdapter:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
          kubeStateMetrics:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
          telemeterClient:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
          openshiftStateMetrics:
            nodeSelector:
              node-role.kubernetes.io/infra: ""
            tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
            - key: infra
              value: reserved
              effect: NoExecute
  tags:
    - infranodes
    - infranodes.ocp
    - infranodes.monitoring

- name: "Annotate openshift-logging correctly"
  environment:
    KUBECONFIG: "{{ openshift_kubeconfig_file }}"
  ansible.builtin.command:
    cmd: "kubectl annotate ns openshift-logging openshift.io/node-selector="
  register: infranodes_annotate
  changed_when: '"openshift-logging annotated" in infranodes_annotate.stdout'
  failed_when: '"error" in infranodes_annotate.stdout'
  tags:
    - infranodes
    - infranodes.ocp
    - infranodes.logging
    - molecule-notest

- name: "Patch openshift-gitops instance"
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig_file }}"
    state: patched
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: ArgoCD
      metadata:
        name: gp-infrastructure-argo
        namespace: openshift-gitops
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  namespaces:
                    - openshift-gitops
                  topologyKey: kubernetes.io/hostname
                weight: 100
        nodeSelector:
          node-role.kubernetes.io/infra: ""
        tolerations:
          - effect: NoSchedule
            key: infra
            value: reserved
          - effect: NoExecute
            key: infra
            value: reserved

- name: "Patch OpenShift Pipelines"
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig_file }}"
    state: patched
    definition:
      apiVersion: pipelines.openshift.io/v1alpha1
      kind: GitopsService
      metadata:
        name: cluster
      spec:
        runOnInfra: true
        tolerations:
          - effect: NoSchedule
            key: infra
            value: reserved
          - effect: NoExecute
            key: infra
            value: reserved

- name: "Patch OpenShift ClusterLogging"
  kubernetes.core.k8s:
    kubeconfig: "{{ openshift_kubeconfig_file }}"
    state: patched
    definition:
      apiVersion: logging.openshift.io/v1
      kind: ClusterLogging
      metadata:
        name: instance
      spec:
        logStore:
          elasticsearch:
            nodeCount: 3
            nodeSelector:
              node-role.kubernetes.io/infra: ''
            tolerations:
              - effect: NoSchedule
                key: infra
                value: reserved
              - effect: NoExecute
                key: infra
                value: reserved
        visualization:
          kibana:
            nodeSelector:
              node-role.kubernetes.io/infra: ''
            tolerations:
              - effect: NoSchedule
                key: infra
                value: reserved
              - effect: NoExecute
                key: infra
                value: reserved

  # TODO: patch openshift-gitops | write molecule tests | authentication server
...
