---
- name: "Add defaultNodeSelector to cluster scheduler"
  k8s:
    kubeconfig: "{{ openshift_kubeconfig_file }}"
    validate_certs: false
    definition:
      apiVersion: config.openshift.io/v1
      kind: Scheduler
      metadata:
        name: cluster
      spec:
        defaultNodeSelector: "{{ infranodes_default_nodeselector }}"
  tags:
    - infranodes
    - infranodes.ocp
    - infranodes.scheduler
...
