---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: create instance host
      ansible.builtin.command:
        cmd: docker run -d --name instance ubuntu:latest sleep infinity

    - name: apt update
      ansible.builtin.command:
        cmd: docker exec instance apt update
      changed_when: false

    - name: install python3
      ansible.builtin.command:
        cmd: docker exec instance apt install -y python3
      changed_when: false

    - name: Create test kind cluster
      ansible.builtin.command:
        cmd: kind create cluster --name infranodes-test --kubeconfig  {{ kubeconfig }}  # yamllint disable-line rule:line-length
      changed_when: false

    - name: Copy kubeconfig to instance
      ansible.builtin.command:
        # yamllint disable-line rule:line-length
        cmd: docker cp "${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig" instance:/root/config
...
