---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: cluster
    groups:
      - k8s
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 1
  inventory:
    hosts:
      all:
        hosts:
          instance:
            kubeconfig: "/root/config"
            openshift_kubeconfig_file: "/root/config"
          localhost:
            kubeconfig: "${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig"
verifier:
  name: ansible
...
